language: node_js
node_js:
- 8.11.1
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn
deploy:
  provider: s3
  access_key_id: AKIAID6JDLWFEURI7Q6Q
  secret_access_key:
    secure: ElKl79tEh0dSNz4/BGPZm06aCMSxonkQdxEea13v78cPaBmlLhOpR3RoOWqd32LI2AfOrC888gDbI4Us3GPWg0NaEZjOhwyRg0kcRKUxUr3CIBhMWHpDWdOl4Tb4oyGHyr+iA4Vb749EktTCVqQfRkJ2YjWakYzFr8sn51DobiNTUKkKqcz2xx5IfD1FYgW7IV0C22XetK83q8TGHdd8lpolh+f/3vI34no4rNts5yLoAc3wEYDqr605/vXf7kkQ2HOFA1saOjizn7RSPmV5YqWGHZ4tF862MxiG1W0wcBuf9dSzItFr6N3GO0yxqcuAfkWe4FvHyYzOUAFa/JrfXTIIbBNnNygwID9gSF2WU1gxqHvzHUn+kgTigaeJIEHHI4cpyZkx7PkqfDa4xF7cb2Ah2pXbNau/856wxsLl7fxkdHbDIUfG3uOxX2lpaKJwYTXfR2p4YnS+SqNMnKo3uspvSGfc2aUqPaj6Wz7d51z3yV9JNE9J/HIghDcJxtYoUyRm90gQrAw2ZRN1mAOOnF8AeRxslroa/7eUpb17VQHjaBZm7wTMIuG//lBVBVbN7f0bJgzQDu1mV9XrGKI2baRdbfOoKqTEBJJc0Ml6i4146bDA/UuPHKN53DAj/4xMwzjX7L4e0TReRyU7bxoAIexMdh5dQfwd8cP+LJpufLM=
  bucket: launch-token
  cache_control: max-age=120
  local_dir: docs
  upload-dir: docs
  acl: public_read
  on:
    repo: launchtoken/landing-page
notifications:
  slack:
    secure: DIsTomwFFmGNO4ZT8ptpbEKo3/oqxxugZFa74B109Fr5652wD3eUkacOu4zw86PpI/WG3xM0/p43fmA2EaUL4UcS7PCJ01Gp4TuopLMSHRW702XRX6K3b1pzhQfk6raD8iCxLzsphiyAZpcBYYz8yYKnE1GLWZ0UhMgzKOVeLUoHMuohawPshessAnupXCc+npoEEhXzHQlFTzf4DF+HxNGF2cZFYYlIm5NnAM69tooCqZMWk4G1VNzzkKefnlQgp8ZW0+eMq5eHX++keubPrq28G10uRp31XuxIliPTlu91CnPFER6MYR5icGIQKdBFZtXCvtvJZ+RsstwFX/JfGou0l4bw2ICs6Cg54yI/bPkzOC2Ejp72xeVhSe78cKbfGRBL4vifyROmaDyT3pHWoiPqv+Dyh8WlDnCwoP338zXeb9r9S5swZWM/w95JimgCliKyg37AzT3YFfRrq2lVZ0sietlZn1/caXQxmoB6OXNAtVoUQ4NlYzXOhPyBwmwQozupshjHa7BLBjEb82Yd5qvThYvZk9x5BjFYsv9LvpogINRMEzgaD3Bw/4iT1tOayQtRdrzMF2pS2SmI7NvQZ1hNWwGQVBe3aoa5tFlGXMfc1bklOVLPoQtBi5RNAIHx61DH3ZtoGdb4+tmqNBPZGdud3kncfvBJ1b9PHrVhSLU=
